# Generated by Django 3.2 on 2021-04-20 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='templates/media')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('categories', models.CharField(choices=[('Categories', 'Category'), ('kiddies', 'kids'), ('Technologies', 'Tech'), ('MEN', 'MEN')], default='Categories', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('marchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
